### ISSUE TITLE
FamixPWBFunctionReturn should be FASTPWBFunctionReturn

### ISSUE THREAD

**Issue by mahugnon** [moosetechnology/PowerBuilderParser#129] opened 2020-12-07 16:15 UTC

**Comment by mahugnon** [comment] 2020-12-07 16:17
Better call it FamixPWBASTFunctionReturn

**Comment by NicolasAnquetil** [comment] 2020-12-21 13:50
Nope, FAST not Famix.
This is the convention
duplicate of #147

**Closed by NicolasAnquetil** 2020-12-21 13:50 UTC
